version: '3.8'

services:
  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: advocacia-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-static:/app/staticfiles
      - backend-media:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-z%tlzrqknoy6j#z-w^i15ri!i-4=*8z%plijxgz0ekef9)r2&y
      - DB_NAME=sistema_advocacia
      - DB_USER=postgres
      - DB_PASSWORD=@Gui020305
      - DB_HOST=easypanel.nacciadvocacia.com.br
      - DB_PORT=5432
      - FERNET_KEY=7RR3-W6pkGEKUwH3u5chq4wS-811puFPoI2jEmNH97M=
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      - advocacia-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: advocacia-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita sobrescrever node_modules do container
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # Para hot-reload funcionar no Windows
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - advocacia-network
    stdin_open: true  # Para o React não fechar
    tty: true

volumes:
  backend-static:
  backend-media:

networks:
  advocacia-network:
    driver: bridge
