# Generated by Django 5.2.6 on 2025-11-01 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_data_criacao_and_more'),
        ('documentos', '0007_anonimizacaoitem_anonimizado_manualmente'),
        ('escritorios', '0011_alter_escritorio_openai_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(verbose_name='Data da Movimentação')),
                ('tipo', models.CharField(choices=[('peticao', 'Petição'), ('despacho', 'Despacho'), ('decisao', 'Decisão'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('certidao', 'Certidão'), ('audiencia', 'Audiência'), ('intimacao', 'Intimação'), ('juntada', 'Juntada'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Protocolo')),
                ('gera_prazo', models.BooleanField(default=False, verbose_name='Gera Prazo')),
                ('prazo_dias', models.IntegerField(blank=True, null=True, verbose_name='Prazo (dias)')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data Limite')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('importante', models.BooleanField(default=False, verbose_name='Marcar como Importante')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='documentos.documento', verbose_name='Documento Vinculado')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(help_text='Formato CNJ: 0000000-00.0000.0.00.0000', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: 0000000-00.0000.0.00.0000', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$')], verbose_name='Número do Processo')),
                ('numero_antigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Antigo')),
                ('tipo', models.CharField(choices=[('civel', 'Cível'), ('trabalhista', 'Trabalhista'), ('criminal', 'Criminal'), ('familia', 'Família'), ('tributario', 'Tributário'), ('previdenciario', 'Previdenciário'), ('consumidor', 'Consumidor'), ('administrativo', 'Administrativo')], max_length=20, verbose_name='Tipo/Área')),
                ('classe', models.CharField(help_text='Ex: Procedimento Comum Cível, Ação Trabalhista, etc.', max_length=100, verbose_name='Classe')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto Principal')),
                ('assuntos_secundarios', models.TextField(blank=True, null=True, verbose_name='Outros Assuntos')),
                ('posicao_cliente', models.CharField(choices=[('autor', 'Autor/Requerente'), ('reu', 'Réu/Requerido'), ('ambos', 'Ambos (Litisconsórcio)')], help_text='Seu cliente é autor, réu ou ambos?', max_length=20, verbose_name='Posição do Cliente')),
                ('tribunal', models.CharField(help_text='Ex: TJSP, TRT-2, Foro de Salto', max_length=100, verbose_name='Tribunal/Foro')),
                ('comarca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comarca')),
                ('vara', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vara')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('data_distribuicao', models.DateField(verbose_name='Data de Distribuição')),
                ('data_citacao', models.DateField(blank=True, null=True, verbose_name='Data de Citação')),
                ('data_audiencia', models.DateField(blank=True, null=True, verbose_name='Próxima Audiência')),
                ('data_sentenca', models.DateField(blank=True, null=True, verbose_name='Data da Sentença')),
                ('data_transito_julgado', models.DateField(blank=True, null=True, verbose_name='Trânsito em Julgado')),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado'), ('sentenciado', 'Sentenciado'), ('transito_julgado', 'Trânsito em Julgado'), ('recurso', 'Em Recurso'), ('execucao', 'Em Execução')], default='andamento', max_length=20, verbose_name='Status')),
                ('tipo_distribuicao', models.CharField(blank=True, help_text='Livre, Prevento, etc.', max_length=50, null=True, verbose_name='Tipo de Distribuição')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Causa')),
                ('valor_condenacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Condenação')),
                ('valor_acordo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do Acordo')),
                ('link_consulta', models.URLField(blank=True, help_text='Link do e-SAJ ou outro sistema', null=True, verbose_name='Link para Consulta')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo do Caso')),
                ('estrategia_juridica', models.TextField(blank=True, null=True, verbose_name='Estratégia Jurídica')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('prazo_proximo', models.DateField(blank=True, null=True, verbose_name='Próximo Prazo')),
                ('alerta_prazo', models.BooleanField(default=False, verbose_name='Alertar sobre Prazo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sigilo', models.BooleanField(default=False, verbose_name='Segredo de Justiça')),
                ('advogado_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável')),
                ('advogados_equipe', models.ManyToManyField(blank=True, related_name='processos_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Equipe')),
                ('cliente_principal', models.ForeignKey(help_text='Cliente principal representado pelo escritório', on_delete=django.db.models.deletion.CASCADE, related_name='processos_principal', to='clientes.cliente', verbose_name='Cliente Principal')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='escritorios.escritorio', verbose_name='Escritório')),
                ('processo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_derivados', to='processos.processo', verbose_name='Processo de Origem')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_distribuicao'],
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Prazo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('prazo_dias', models.IntegerField(verbose_name='Prazo (dias)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('cumprido', 'Cumprido'), ('vencido', 'Vencido')], default='pendente', max_length=10, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('data_cumprimento', models.DateTimeField(blank=True, null=True, verbose_name='Cumprido em')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('alertar_dias_antes', models.IntegerField(default=3, verbose_name='Alertar X dias antes')),
                ('alerta_enviado', models.BooleanField(default=False, verbose_name='Alerta Enviado')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_gerados', to='processos.movimentacao', verbose_name='Movimentação Origem')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['data_limite', 'prioridade'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parte', models.CharField(choices=[('autor', 'Autor/Requerente'), ('reu', 'Réu/Requerido'), ('terceiro', 'Terceiro Interessado'), ('assistente', 'Assistente'), ('ministerio_publico', 'Ministério Público')], max_length=30, verbose_name='Tipo de Parte')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], max_length=10, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('advogado_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Advogado')),
                ('advogado_oab', models.CharField(blank=True, max_length=20, null=True, verbose_name='OAB')),
                ('representado_escritorio', models.BooleanField(default=False, help_text='Marque se esta parte é representada pelo seu escritório', verbose_name='Representado pelo Escritório')),
                ('cliente_vinculado', models.ForeignKey(blank=True, help_text='Se esta parte for um cliente cadastrado no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_processos', to='clientes.cliente', verbose_name='Cliente do Escritório')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
                'ordering': ['tipo_parte', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processo', verbose_name='Processo'),
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conciliacao', 'Conciliação'), ('instrucao', 'Instrução e Julgamento'), ('inicial', 'Audiência Inicial'), ('una', 'Audiência Una'), ('justificacao', 'Justificação'), ('outras', 'Outras')], max_length=20, verbose_name='Tipo de Audiência')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('link_virtual', models.URLField(blank=True, null=True, verbose_name='Link (Audiência Virtual)')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('adiada', 'Adiada')], default='agendada', max_length=15, verbose_name='Status')),
                ('pauta', models.TextField(blank=True, null=True, verbose_name='Pauta/Objetivo')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado/Ata')),
                ('alertar', models.BooleanField(default=True, verbose_name='Enviar Alerta')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiencias_ata', to='documentos.documento', verbose_name='Ata da Audiência')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Audiência',
                'verbose_name_plural': 'Audiências',
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['escritorio', 'cliente_principal', '-data_distribuicao'], name='processos_p_escrito_56409e_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['numero_processo'], name='processos_p_numero__d17be0_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['status'], name='processos_p_status_b5122a_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['advogado_responsavel', 'status'], name='processos_p_advogad_0290ba_idx'),
        ),
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['processo', 'status', 'data_limite'], name='processos_p_process_3f93e1_idx'),
        ),
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['responsavel', 'status', 'data_limite'], name='processos_p_respons_3f1300_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['processo', '-data_movimentacao'], name='processos_m_process_beda39_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['tipo', '-data_movimentacao'], name='processos_m_tipo_77350a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['processo', 'status', 'data_hora'], name='processos_a_process_c325bb_idx'),
        ),
    ]
