# Generated by Django 5.2.6 on 2025-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='assunto',
            field=models.CharField(blank=True, help_text='Será preenchido automaticamente pela API do tribunal', max_length=200, null=True, verbose_name='Assunto Principal'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classe',
            field=models.CharField(blank=True, help_text='Ex: Procedimento Comum Cível, Ação Trabalhista, etc.', max_length=100, null=True, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_distribuicao',
            field=models.DateField(blank=True, help_text='Será preenchida automaticamente pela API', null=True, verbose_name='Data de Distribuição'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='posicao_cliente',
            field=models.CharField(blank=True, choices=[('autor', 'Autor/Requerente'), ('reu', 'Réu/Requerido'), ('ambos', 'Ambos (Litisconsórcio)')], help_text='Seu cliente é autor, réu ou ambos?', max_length=20, null=True, verbose_name='Posição do Cliente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('civel', 'Cível'), ('trabalhista', 'Trabalhista'), ('criminal', 'Criminal'), ('familia', 'Família'), ('tributario', 'Tributário'), ('previdenciario', 'Previdenciário'), ('consumidor', 'Consumidor'), ('administrativo', 'Administrativo')], help_text='Será preenchido automaticamente pela API do tribunal', max_length=20, null=True, verbose_name='Tipo/Área'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tribunal',
            field=models.CharField(blank=True, help_text='Ex: TJSP, TRT-2, Foro de Salto - Será preenchido pela API', max_length=100, null=True, verbose_name='Tribunal/Foro'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='uf',
            field=models.CharField(blank=True, help_text='Será preenchido automaticamente pela API', max_length=2, null=True, verbose_name='UF'),
        ),
    ]
