# Generated by Django 5.2.6 on 2025-10-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.TextField(help_text='O prompt ou contexto fornecido pelo usuário para a análise.', verbose_name='Contexto da Análise')),
                ('resultado', models.TextField(verbose_name='Resultado da Análise')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='consultas.consulta')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
