# Generated by Django 5.2.6 on 2025-10-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('escritorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='escritorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='escritorios.escritorio'),
        ),
    ]
