# Generated by Django 5.2.6 on 2025-10-03 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20251002_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='advogado_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Advogado Responsável'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='area_interesse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Jurídica de Interesse'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='como_chegou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Como Chegou ao Escritório'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_primeiro_atendimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Primeiro Atendimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Alternativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='historico_relacionamento',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Relacionamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia (PJ)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='outros_advogados',
            field=models.TextField(blank=True, null=True, verbose_name='Outros Advogados que já o Representaram'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencia_contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferência de Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão/Ocupação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social (PJ)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regime_bens',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Regime de Bens'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='restricoes',
            field=models.TextField(blank=True, null=True, verbose_name='Restrições Específicas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_cliente',
            field=models.CharField(default='Ativo', max_length=50, verbose_name='Status do Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço (Legado)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(help_text='Para Pessoa Física', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Legado)'),
        ),
    ]
