# Generated by Django 5.0.6 on 2025-10-02 10:38

from django.db import migrations

def link_existing_data(apps, schema_editor):
    """
    Cria um Escritório Padrão e associa todos os usuários e clientes existentes a ele.
    """
    Escritorio = apps.get_model('escritorios', 'Escritorio')
    PerfilUsuario = apps.get_model('escritorios', 'PerfilUsuario')
    User = apps.get_model('auth', 'User')
    Cliente = apps.get_model('clientes', 'Cliente')

    # 1. Cria o escritório padrão
    default_escritorio, created = Escritorio.objects.get_or_create(nome="Escritório Padrão")

    # 2. Associa usuários existentes ao escritório padrão
    for user in User.objects.all():
        PerfilUsuario.objects.get_or_create(user=user, defaults={'escritorio': default_escritorio})

    # 3. Associa clientes existentes ao escritório padrão
    Cliente.objects.filter(escritorio__isnull=True).update(escritorio=default_escritorio)


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('clientes', '0002_cliente_escritorio'),
        ('auth', '__latest__'), # Depende do app de autenticação
    ]

    operations = [
        migrations.RunPython(link_existing_data),
    ]