# Generated by Django 5.2.6 on 2025-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0002_auto_20251002_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='data_expiracao_teste',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração do Teste'),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='status_assinatura',
            field=models.CharField(choices=[('trial', 'Em Teste'), ('active', 'Ativo'), ('expired', 'Expirado'), ('canceled', 'Cancelado')], default='trial', max_length=20, verbose_name='Status da Assinatura'),
        ),
    ]
