# Generated by Django 5.2.6 on 2025-10-02 14:23

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0003_escritorio_data_expiracao_teste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='openai_api_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Chave de API da OpenAI'),
        ),
    ]
