# Generated by Django 5.2.6 on 2025-10-02 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0004_escritorio_openai_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='escritorios.escritorio')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
