# Generated by Django 5.2.6 on 2025-10-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0006_escritorio_bairro_escritorio_cep_escritorio_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Permissão')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename da Permissão')),
            ],
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Papel')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to='escritorios.escritorio')),
                ('permissoes', models.ManyToManyField(blank=True, related_name='papeis', to='escritorios.permissao')),
            ],
            options={
                'unique_together': {('nome', 'escritorio')},
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='papeis',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='escritorios.papel'),
        ),
    ]
