# Generated by Django 5.2.6 on 2025-10-04 15:04

from django.db import migrations

PERMISSOES = [
    # Clientes
    ('ver_cliente', 'Ver Cliente'),
    ('criar_cliente', 'Criar Cliente'),
    ('editar_cliente', 'Editar Cliente'),
    ('deletar_cliente', 'Deletar Cliente'),
    # Consultas
    ('ver_consulta', 'Ver Consulta'),
    ('criar_consulta', 'Criar Consulta'),
    ('deletar_consulta', 'Deletar Consulta'),
    # Análises
    ('ver_analise', 'Ver Análise'),
    ('criar_analise', 'Criar Análise'),
    ('deletar_analise', 'Deletar Análise'),
    # Escritório
    ('gerenciar_escritorio', 'Gerenciar Dados do Escritório'),
    ('gerenciar_membros', 'Gerenciar Membros'),
    ('gerenciar_papeis', 'Gerenciar Papéis e Permissões'),
]

def criar_permissoes(apps, schema_editor):
    Permissao = apps.get_model('escritorios', 'Permissao')
    for codename, nome in PERMISSOES:
        Permissao.objects.get_or_create(codename=codename, defaults={'nome': nome})

def remover_permissoes(apps, schema_editor):
    Permissao = apps.get_model('escritorios', 'Permissao')
    codenames = [p[0] for p in PERMISSOES]
    Permissao.objects.filter(codename__in=codenames).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0007_permissao_papel_perfilusuario_papeis'),
    ]

    operations = [
        migrations.RunPython(criar_permissoes, reverse_code=remover_permissoes),
    ]