# Generated by Django 5.2.6 on 2025-10-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0008_auto_20251004_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='escritorios.escritorio'),
        ),
    ]
