# Generated by Django 5.2.6 on 2025-10-04 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('escritorios', '0009_alter_perfilusuario_escritorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRetencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_retencao', models.PositiveIntegerField(default=365, help_text='Número de dias que os logs devem ser mantidos (padrão: 1 ano)', verbose_name='Dias de Retenção')),
                ('habilitar_log_leitura', models.BooleanField(default=False, help_text='Se deve registrar operações de VIEW (pode gerar muitos logs)', verbose_name='Habilitar Log de Leitura')),
                ('habilitar_exportacao_automatica', models.BooleanField(default=False, help_text='Se deve exportar logs antigos antes de excluir', verbose_name='Exportação Automática')),
                ('escritorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_auditoria', to='escritorios.escritorio', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Configuração de Retenção',
                'verbose_name_plural': 'Configurações de Retenção',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(help_text='Nome do usuário no momento da ação (para histórico)', max_length=255, verbose_name='Nome do Usuário')),
                ('escritorio_id', models.IntegerField(blank=True, help_text='ID do escritório no momento da ação', null=True, verbose_name='ID do Escritório')),
                ('escritorio_nome', models.CharField(blank=True, help_text='Nome do escritório no momento da ação', max_length=255, verbose_name='Nome do Escritório')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(help_text='Descrição da ação realizada', verbose_name='Descrição')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('objeto_repr', models.CharField(blank=True, help_text='String representation do objeto no momento da ação', max_length=255, verbose_name='Representação do Objeto')),
                ('modelo_nome', models.CharField(blank=True, db_index=True, help_text='Nome do modelo afetado (Cliente, Consulta, etc.)', max_length=100, verbose_name='Nome do Modelo')),
                ('endpoint', models.CharField(blank=True, help_text='URL do endpoint acessado', max_length=500, verbose_name='Endpoint')),
                ('metodo_http', models.CharField(blank=True, help_text='GET, POST, PUT, PATCH, DELETE', max_length=10, verbose_name='Método HTTP')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador/cliente utilizado', verbose_name='User Agent')),
                ('dados_antigos', models.JSONField(blank=True, help_text='Estado anterior do objeto (para UPDATE e DELETE)', null=True, verbose_name='Dados Antigos')),
                ('dados_novos', models.JSONField(blank=True, help_text='Estado novo do objeto (para CREATE e UPDATE)', null=True, verbose_name='Dados Novos')),
                ('campos_alterados', models.JSONField(blank=True, help_text='Lista de campos que foram modificados', null=True, verbose_name='Campos Alterados')),
                ('sucesso', models.BooleanField(default=True, help_text='Se a ação foi executada com sucesso', verbose_name='Sucesso')),
                ('erro_mensagem', models.TextField(blank=True, help_text='Mensagem de erro se a ação falhou', verbose_name='Mensagem de Erro')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'escritorio_id'], name='escritorios_timesta_178dea_idx'), models.Index(fields=['usuario', '-timestamp'], name='escritorios_usuario_ae6625_idx'), models.Index(fields=['acao', '-timestamp'], name='escritorios_acao_3832dc_idx'), models.Index(fields=['modelo_nome', '-timestamp'], name='escritorios_modelo__c7bc0b_idx')],
            },
        ),
    ]
