# Generated by Django 5.2.6 on 2025-11-01 14:21

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0010_auditlogretencao_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='openai_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Chave de API da OpenAI'),
        ),
    ]
