# Generated by Django 5.2.6 on 2025-10-05 14:12

import django.core.validators
import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_data_criacao_and_more'),
        ('escritorios', '0010_auditlogretencao_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='description', help_text='Nome do ícone do Material-UI (ex: description, article, folder)', max_length=50, verbose_name='Ícone Material-UI')),
                ('cor', models.CharField(default='primary', help_text='Cor do Material-UI (primary, secondary, success, error, warning, info)', max_length=20, verbose_name='Cor')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_documentos', to='escritorios.escritorio', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('escritorio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Tag')),
                ('cor', models.CharField(default='#1976d2', help_text='Cor em formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Cor Hex')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_documentos', to='escritorios.escritorio', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
                'unique_together': {('escritorio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=documentos.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'txt', 'xlsx', 'xls'])], verbose_name='Arquivo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original do Arquivo')),
                ('tipo_arquivo', models.CharField(max_length=10, verbose_name='Tipo/Extensão')),
                ('tamanho', models.BigIntegerField(verbose_name='Tamanho em Bytes')),
                ('hash_md5', models.CharField(blank=True, help_text='Para detectar duplicatas', max_length=32, verbose_name='Hash MD5')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_documento', models.DateField(blank=True, help_text='Data real do documento físico/assinatura', null=True, verbose_name='Data do Documento')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('confidencial', models.BooleanField(default=False, help_text='Requer permissão especial para visualizar', verbose_name='Confidencial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Número de Visualizações')),
                ('downloads', models.IntegerField(default=0, verbose_name='Número de Downloads')),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído do documento para busca', verbose_name='Texto Extraído (OCR)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.categoria', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente', verbose_name='Cliente')),
                ('documento_pai', models.ForeignKey(blank=True, help_text='Referência à versão anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='documentos.documento', verbose_name='Documento Original')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='escritorios.escritorio', verbose_name='Escritório')),
                ('usuario_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez Upload')),
                ('tags', models.ManyToManyField(blank=True, related_name='documentos', to='documentos.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['escritorio', 'cliente', '-data_upload'], name='documentos__escrito_dff850_idx'), models.Index(fields=['escritorio', 'categoria', '-data_upload'], name='documentos__escrito_03c5eb_idx'), models.Index(fields=['hash_md5'], name='documentos__hash_md_92da4f_idx')],
            },
        ),
    ]
