# Generated by Django 5.2.6 on 2025-10-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('escritorios', '0010_auditlogretencao_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analise', models.CharField(choices=[('resumo', 'Resumo Executivo'), ('extracao_dados', 'Extração de Dados'), ('juridico', 'Análise Jurídica'), ('contrato', 'Análise de Contrato'), ('risco', 'Análise de Risco'), ('personalizado', 'Análise Personalizada')], max_length=20, verbose_name='Tipo de Análise')),
                ('prompt_personalizado', models.TextField(blank=True, help_text='Instruções específicas para a IA (apenas para análise personalizada)', verbose_name='Prompt Personalizado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=15, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado da Análise')),
                ('dados_estruturados', models.JSONField(blank=True, default=dict, help_text='Dados extraídos em formato JSON (para extração de dados)', verbose_name='Dados Estruturados')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('tempo_processamento', models.DurationField(blank=True, null=True, verbose_name='Tempo de Processamento')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('tokens_usados', models.IntegerField(default=0, verbose_name='Tokens Utilizados')),
                ('custo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Estimado (USD)')),
                ('modelo_ia', models.CharField(default='gpt-4', max_length=50, verbose_name='Modelo de IA Utilizado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='documentos.documento', verbose_name='Documento')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='escritorios.escritorio', verbose_name='Escritório')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que solicitou')),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['escritorio', '-data_solicitacao'], name='documentos__escrito_fe0885_idx'), models.Index(fields=['documento', '-data_solicitacao'], name='documentos__documen_937045_idx'), models.Index(fields=['status'], name='documentos__status_628dd8_idx')],
            },
        ),
    ]
