# Generated by Django 5.2.6 on 2025-10-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoanaliseia',
            name='prompt_personalizado',
            field=models.TextField(blank=True, help_text='Instruções específicas para a IA (apenas para análise personalizada)', null=True, verbose_name='Prompt Personalizado'),
        ),
    ]
