# Generated by Django 5.2.6 on 2025-10-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_data_criacao_and_more'),
        ('documentos', '0004_alter_documentoanaliseia_prompt_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
