# Generated by Django 5.2.6 on 2025-10-07 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_documento_cliente'),
        ('escritorios', '0010_auditlogretencao_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnonimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('revertido', 'Revertido')], default='pendente', max_length=15, verbose_name='Status')),
                ('texto_original', models.TextField(help_text='Backup do texto antes da anonimização', verbose_name='Texto Original')),
                ('texto_anonimizado', models.TextField(blank=True, verbose_name='Texto Anonimizado')),
                ('anonimizar_nomes', models.BooleanField(default=True, verbose_name='Anonimizar Nomes')),
                ('anonimizar_cpf', models.BooleanField(default=True, verbose_name='Anonimizar CPF')),
                ('anonimizar_rg', models.BooleanField(default=True, verbose_name='Anonimizar RG')),
                ('anonimizar_enderecos', models.BooleanField(default=True, verbose_name='Anonimizar Endereços')),
                ('anonimizar_telefones', models.BooleanField(default=True, verbose_name='Anonimizar Telefones')),
                ('anonimizar_emails', models.BooleanField(default=True, verbose_name='Anonimizar E-mails')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('data_reversao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Reversão')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonimizacoes', to='documentos.documento', verbose_name='Documento')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonimizacoes', to='escritorios.escritorio', verbose_name='Escritório')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonimizacoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que solicitou')),
            ],
            options={
                'verbose_name': 'Anonimização de Documento',
                'verbose_name_plural': 'Anonimizações de Documentos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='AnonimizacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dado', models.CharField(choices=[('nome', 'Nome'), ('cpf', 'CPF'), ('rg', 'RG'), ('endereco', 'Endereço'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Dado')),
                ('valor_original', models.TextField(help_text='Valor real encontrado no documento', verbose_name='Valor Original')),
                ('valor_anonimizado', models.CharField(help_text='Placeholder usado na substituição (ex: NOME1, CPF1)', max_length=100, verbose_name='Valor Anonimizado')),
                ('posicao_inicio', models.IntegerField(blank=True, help_text='Posição do caractere no texto original', null=True, verbose_name='Posição Início')),
                ('posicao_fim', models.IntegerField(blank=True, null=True, verbose_name='Posição Fim')),
                ('contexto', models.CharField(blank=True, help_text='Trecho do texto ao redor para validação', max_length=200, verbose_name='Contexto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('anonimizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='documentos.documentoanonimizacao', verbose_name='Anonimização')),
            ],
            options={
                'verbose_name': 'Item de Anonimização',
                'verbose_name_plural': 'Itens de Anonimização',
                'ordering': ['posicao_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='documentoanonimizacao',
            index=models.Index(fields=['escritorio', '-data_solicitacao'], name='documentos__escrito_7a604c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoanonimizacao',
            index=models.Index(fields=['documento', '-data_solicitacao'], name='documentos__documen_a44a34_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoanonimizacao',
            index=models.Index(fields=['status'], name='documentos__status_e2f7a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anonimizacaoitem',
            unique_together={('anonimizacao', 'valor_anonimizado')},
        ),
    ]
