# Generated by Django 5.2.6 on 2025-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documentoanonimizacao_anonimizacaoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonimizacaoitem',
            name='anonimizado_manualmente',
            field=models.BooleanField(default=False, help_text='Indica se foi anonimizado manualmente pelo usuário', verbose_name='Anonimizado Manualmente'),
        ),
    ]
